# Generated by Django 5.1.1 on 2024-10-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, choices=[('Портрет', 'Портрет'), ('Пейзаж', 'Пейзаж'), ('Исторический', 'Исторический'), ('Батальный', 'Батальный'), ('Натюрморт', 'Натюрморт'), ('Бытовой', 'Бытовой'), ('Мифиологический', 'Мифиологический'), ('Анималистический', 'Анималистический'), ('Архитектурный', 'Архитектурный')], max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категория',
                'ordering': ['-category_name'],
            },
        ),
        migrations.CreateModel(
            name='Painter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=255, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['-first_name'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_name', models.CharField(max_length=255, verbose_name='Стиль')),
                ('style_description', models.CharField(blank=True, max_length=255, verbose_name='Описание стиля')),
            ],
            options={
                'verbose_name': 'Стиль',
                'verbose_name_plural': 'Стили',
                'ordering': ['-style_name'],
            },
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography_text', models.TextField(blank=True, verbose_name='Текст биографии')),
                ('contact_info', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Контактная информация')),
                ('painter_picture', models.ImageField(blank=True, upload_to='icon/', verbose_name='Фотография автора')),
                ('painter', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biography', to='shop.painter', verbose_name='Painter')),
            ],
            options={
                'verbose_name': 'Биография',
                'verbose_name_plural': 'Биографии',
                'ordering': ['-biography_text'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название картины')),
                ('public_date', models.DateField(verbose_name='Дата публикации картины')),
                ('availability', models.BooleanField(choices=[(True, 'В наличии'), (False, 'Нет в наличии')], default=True, verbose_name='Наличие')),
                ('is_original', models.BooleanField(choices=[(True, 'Оригинал'), (False, 'Копия')], verbose_name='Оригинал')),
                ('history', models.CharField(blank=True, max_length=1024, verbose_name='История картины')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('cover_picture', models.ImageField(upload_to='images/', verbose_name='Картина')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pictures', to='shop.painter', verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Categories', to='shop.category', verbose_name='Категория')),
                ('style', models.ManyToManyField(blank=True, related_name='Styles', to='shop.style', verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Картина',
                'verbose_name_plural': 'Картины',
                'ordering': ['-title'],
            },
        ),
    ]
