# Generated by Django 5.1.1 on 2024-10-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='biography_text',
            field=models.TextField(blank=True, unique=True, verbose_name='Текст биографии'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, verbose_name='Контактная информация'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='cover_picture',
            field=models.ImageField(unique=True, upload_to='images/', verbose_name='Картина'),
        ),
    ]
