# Generated by Django 5.1.2 on 2024-10-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Painter', 'Художник'), ('Client', 'Покупатель')], default='Client', max_length=10, verbose_name='Роль'),
        ),
    ]
