# Generated by Django 5.1.1 on 2024-10-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_biography_biography_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='cover_picture',
            field=models.ImageField(unique=True, upload_to=' ', verbose_name='Картина'),
        ),
    ]
