# Generated by Django 5.1.2 on 2024-10-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='public_date',
            field=models.DateField(null=True, verbose_name='Дата публикации картины'),
        ),
    ]
