# Generated by Django 5.1.2 on 2024-10-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_picture_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='painter_picture',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Фотография автора'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='cover_picture',
            field=models.ImageField(unique=True, upload_to='pitcure/', verbose_name='Картина'),
        ),
    ]
