# Generated by Django 5.1.2 on 2024-10-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_biography_painter_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='cover_picture',
            field=models.ImageField(unique=True, upload_to='', verbose_name='Картина'),
        ),
    ]
