# Generated by Django 5.1.2 on 2024-10-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='painter_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Фотография автора'),
        ),
    ]
